bfq: fix compiler error
after commit dcc8e74cdbe1f8fd87ff9ba88e9ae429e373824c ("block: do not merge requests without consulting with io scheduler")

/home/adek/kernel/whyred/block/bfq-iosched.c:1624:14: error: implicit declaration of function 'elv_rq_merge_ok' [-Werror,-Wimplicit-function-declaration]
        if (__rq && elv_rq_merge_ok(__rq, bio)) {
                    ^

Original patch was from here: https://github.com/RaphielGang/stormguard_kernel/commit/85fa80da940e7e0efa9f12b46b66e0a6a79f37bb ("bfq: do not merge requests without consulting with io scheduler")

Change-Id: I2f1efb6af8b004c5edb9ebaa158e0a08606da817
Signed-off-by: Adek Maulana <adekzmaulana@gmail.com>